### ISSUE TITLE
Skype giving errors

### ISSUE THREAD

**Issue by steve6375** [BahKoo/ChocolateStore#12]
Download Failed: http://download.skype.com/3694814915aaa38100bfa0933f948e65/partner/59/SkypeSetup.exe
System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.GetResponse()
   at ChocolateStore.PackageCacher.DownloadFile(String url, String destination) in C:\temp\ChocStore\src\ChocolateStore\
PackageCacher.cs:line 72
Download Failed: http://download.skype.com/SkypeSetupFull.exe
System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.GetResponse()
   at ChocolateStore.PackageCacher.DownloadFile(String url, String destination) in C:\temp\ChocStore\src\ChocolateStore\
PackageCacher.cs:line 72

**Comment by steve6375** [comment]
Also WinRar...
