### ISSUE TITLE
Can't download mpc-be

### ISSUE THREAD

**Issue by laggingreflex** [BahKoo/ChocolateStore#19]
I get this error when downloading mpc-be

```
Reading package 'mpc-be'
package URL: 'https://chocolatey.org/api/v2/package/mpc-be/1.5.1.171106'
Skipped: mpc-be.1.5.1.171106.nupkg - File already exists on disk.
Download Failed: https://sourceforge.net/projects/mpcbe/files/MPC-BE/Release%20builds/1.5.1/MPC-BE.1.5.1.x86-installer.zip/download
System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.HttpWebRequest.GetResponse()
   at ChocolateStore.PackageCacher.DownloadFile(String url, String destination) in C:\...\ChocolateStore\PackageCacher.cs:line 83
Download Failed: https://sourceforge.net/projects/mpcbe/files/MPC-BE/Release%20builds/1.5.1/MPC-BE.1.5.1.x64-installer.zip/download
System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.HttpWebRequest.GetResponse()
   at ChocolateStore.PackageCacher.DownloadFile(String url, String destination) in C:\...\ChocolateStore\PackageCacher.cs:line 83
```
Installs ok when installed directly

```
Chocolatey v0.10.8
Installing the following packages:
mpc-be
By installing you accept licenses for the packages.
Progress: Downloading mpc-be 1.5.1.171106... 100%

mpc-be v1.5.1.171106 [Approved]
mpc-be package files install completed. Performing other installation steps.
Downloading mpc-be 64 bit
  from 'https://sourceforge.net/projects/mpcbe/files/MPC-BE/Release%20builds/1.5.1/MPC-BE.1.5.1.x64-installer.zip/download'
Progress: 100% - Completed download of C:\Users\...\AppData\Local\Temp\chocolatey\mpc-be\1.5.1.171106\MPC-BE.1.5.1.x64-installer.zip (12.33 MB).
Download of MPC-BE.1.5.1.x64-installer.zip (12.33 MB) completed.
Hashes match.
Extracting C:\Users\...\AppData\Local\Temp\chocolatey\mpc-be\1.5.1.171106\MPC-BE.1.5.1.x64-installer.zip to C:\ProgramData\chocolatey\lib\mpc-be\tools...
C:\ProgramData\chocolatey\lib\mpc-be\tools
Installing mpc-be...
mpc-be has been installed.
PATH environment variable does not have "C:\Program Files\MPC-BE x64\" in it. Adding...
  mpc-be can be automatically uninstalled.
Environment Vars (like PATH) have changed. Close/reopen your shell to
 see the changes (or in powershell/cmd.exe just type `refreshenv`).
 The install of mpc-be was successful.
  Software installed to 'C:\Program Files\MPC-BE x64\'
```

**Comment by BahKoo** [comment]
It looks like a proxy is required to download the files in this package. It looks like chocolatey has a strategy for doing this in [Get-WebFile.ps1](https://github.com/chocolatey/choco/blob/master/src/chocolatey.resources/helpers/functions/Get-WebFile.ps1) in the chocolatey repository.

I think we would have to implement something similar in our .NET code.

I have no immediate plans to look at this issue further but would accept a pull request if anyone wants to look at it.
