### ISSUE TITLE
libreoffice-fresh does not download .MSI file

### ISSUE THREAD

**Issue by steve6375** [BahKoo/ChocolateStore#22]
v6.0.5 does not download the .msi file
libreoffice 5.4.4 gives no error but cannot see .msi file.

> Running ChocolateStore to make package...
> Downloading: libreoffice-fresh.6.0.5.nupkg
> Download Failed: https://download.documentfoundation.org/libreoffice/stable/6.0.5/win/x86/LibreOffice_6.0.5_Win_x86.msi
> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Unable to read data from the
> transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibl
> y closed by the remote host
>    at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
>    at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
>    --- End of inner exception stack trace ---
>    at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
>    at System.Net.FixedSizeReader.ReadPacket(Byte[] buffer, Int32 offset, Int32 count)
>    at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
>    at System.Net.TlsStream.CallProcessAuthentication(Object state)
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
>    at System.Net.TlsStream.ProcessAuthentication(LazyAsyncResult result)
>    at System.Net.TlsStream.Write(Byte[] buffer, Int32 offset, Int32 size)
>    at System.Net.PooledStream.Write(Byte[] buffer, Int32 offset, Int32 size)
>    at System.Net.ConnectStream.WriteHeaders(Boolean async)
>    --- End of inner exception stack trace ---
>    at System.Net.HttpWebRequest.GetResponse()
>    at ChocolateStore.PackageCacher.DownloadFile(String url, String destination) in C:\temp\ChocStore\src\ChocolateStore\PackageCacher.cs:line 72
> Download Failed: https://download.documentfoundation.org/libreoffice/stable/6.0.5/win/x86_64/LibreOffice_6.0.5_Win_x64.msi
> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Unable to read data from the
> transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibl
> y closed by the remote host
>    at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
>    at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
>    --- End of inner exception stack trace ---
>    at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
>    at System.Net.FixedSizeReader.ReadPacket(Byte[] buffer, Int32 offset, Int32 count)
>    at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
>    at System.Net.TlsStream.CallProcessAuthentication(Object state)
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
>    at System.Net.TlsStream.ProcessAuthentication(LazyAsyncResult result)
>    at System.Net.TlsStream.Write(Byte[] buffer, Int32 offset, Int32 size)
>    at System.Net.PooledStream.Write(Byte[] buffer, Int32 offset, Int32 size)
>    at System.Net.ConnectStream.WriteHeaders(Boolean async)
>    --- End of inner exception stack trace ---
>    at System.Net.HttpWebRequest.GetResponse()
>    at ChocolateStore.PackageCacher.DownloadFile(String url, String destination) in C:\temp\ChocStore\src\ChocolateStore\PackageCacher.cs:line 72
>

**Comment by harkx** [comment]
Works on my end so this must have been a one time thing ..
