### ISSUE TITLE
System.UnauthorizedAccessException 

### ISSUE THREAD

**Issue by Aabayoumy** [BahKoo/ChocolateStore#25]
I got this error in powershell & CMD !
I'm the oner of folder and give modify permition to everyone !

[D:\]# .\ChocolateStore.exe d:\choco https://chocolatey.org/packages/DellCommandUpdate/
Downloading:
Download Failed: https://chocolatey.org/packages/DellCommandUpdate/
System.UnauthorizedAccessException: Access to the path 'd:\choco' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at ChocolateStore.PackageCacher.DownloadFile(String url, String destination)
System.NotSupportedException: The given path's format is not supported.
   at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Ionic.Zip.ZipFile.get_ReadStream()
   at Ionic.Zip.ZipFile.ReadIntoInstance(ZipFile zf)
   at Ionic.Zip.ZipFile.Read(String fileName, TextWriter statusMessageWriter, Encoding encoding, EventHandler`1 readProgress)
   at ChocolateStore.PackageCacher.CachePackage(String dir, String url)
   at ChocolateStore.Program.Main(String[] args)

**Comment by BahKoo** [comment]
I can't reproduce the problem. Can you rebuild the latest version and try again? Are you having this problem with all packages or only DellCommandUpdate?

**Comment by Aabayoumy** [comment]
it's for all packages
it's working only when point the tore to external usb drive :)

**Comment by BahKoo** [comment]
It seems like there's some permission issue in your setup. Does it work if you use a location in your %APPDATA% or %TEMP% folders?
